vim.o.termguicolors = true
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colors"
require "user.cmp"
require "user.lsp"
require "user.autopairs"
require "user.lualine"
require "user.telescope"
require "user.colorizer"
require "user.nvimtree"
